### ISSUE TITLE
SyntaxError: Octal literals are not allowed in strict mode.

### ISSUE THREAD

**Issue by dnblank123** [ArturoDent/find-and-transform#15]
To find and increment:
> img001.png

Keybind I used:
```
    {
        "key": "ctrl+alt+r",                  // img
        "command": "findInCurrentFile",
        "args": {      
          "find": "img(\\d+)",
          "replace": "img$${ return $1 + 1 }$$",
          "isRegex": true
        }
    },
```
Error
```
SyntaxError: Octal literals are not allowed in strict mode.
	at Function (<anonymous>)
	at c:\Users\Admin\.vscode\extensions\arturodent.find-and-transform-4.6.0\src\resolveVariables.js:250:20
	at [Symbol.replace] (<anonymous>)
	at String.replaceAll (<anonymous>)
	at exports.resolveVariables (c:\Users\Admin\.vscode\extensions\arturodent.find-and-transform-4.6.0\src\resolveVariables.js:221:28)
	at c:\Users\Admin\.vscode\extensions\arturodent.find-and-transform-4.6.0\src\transform.js:778:33
	at Object.edit (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:51852)
	at exports.replaceInWholeDocument (c:\Users\Admin\.vscode\extensions\arturodent.find-and-transform-4.6.0\src\transform.js:769:10)
	at async exports.splitFindCommands (c:\Users\Admin\.vscode\extensions\arturodent.find-and-transform-4.6.0\src\parseCommands.js:113:7)
	at async exports.startFindInCurrentFile (c:\Users\Admin\.vscode\extensions\arturodent.find-and-transform-4.6.0\src\drivers.js:58:5)
```

**Comment by ArturoDent** [comment]
I have been looking into this.  The extension uses strict mode to run any code in a `jsOperation` like `$${ some code here }$$` which may appear in a `replace` or a `run` value.  That I won't change for security reasons.  Strict mode does unfortunately interpret an integer like `003` or `02` as an octal literal and errors.  

Even running your code: `$${ return $1 + 1 }$$` without strict mode enabled doesn't help much.  Although it won't error, javascript still interprets `003` as just `3` for math operation - in other words it discards those leading zeros.

I think the only way to solve this issue is within your keybinding jsOperation.  This keybinding appears to work for me:

```jsonc
{
    "key": "ctrl+alt+r",
    "command": "findInCurrentFile",
    "args": {      
      "find": "img(0*)(\\d*)",

      "replace": [
        "$${",
          "let numZeros = '$1'.length;",     // number of zeros after 'img' and before other digits
          "const sum = $2 + 1;",             // works
          // "const sum = $2 / n;",          // works for any n
          // "const sum = $2 - n;",          // works for any n
          
              // if sum > $2, might have to subtract some zeros
              // if length of the sum > length of $2
          "if (sum > $2) numZeros -= (sum.toString().length - '$2'.length);",    

              // if sum < $2, might have to add some zeros
              // if length of the sum < length of $2
          "if (sum < $2) numZeros += ('$2'.length - sum.toString().length);",    
          
          "return 'img'.padEnd(3+numZeros, '0') + sum;",  // 3 is the length of 'img'
        "}$$",
      ],
      "isRegex": true,
      "restrictFind": "line"
    }
}
```
Notice the `"find": "img(0*)(\\d*)",` is a little different to isolate the leading 0's in their own capture group `$1`.

Then zeros are removed if the new sum is longer (i.e., the string itself is longer - `sum.toString().length`) than the old `$2`'s length.    

You only need this line:

```jsonc
"if (sum < $2) numZeros += ('$2'.length - sum.toString().length);", 
```

if your new `sum` might be less than the old `$2` - by subtracting from it or division, etc.  Since you are adding to it you can comment that line out and only use the `if (sum > $2)...` line.  Or just leave it active for future cases, it won't do anything in a case like addition (of a positive number).  

Test this and let me know if it works for you.  Thank you.

**Comment by dnblank123** [comment]
I tried your keybind solution, and it works, thanks!
