### ISSUE TITLE
use the input text in Find text box

### ISSUE THREAD

**Issue by Haale** [ArturoDent/find-and-transform#21]
Usually, we use the vscode Find&Replace input box (ctrl+F) to search for the thing we want.
I think it will be very interesting when the "find" command in Find-Transform withdraws the text of vscode Find Box and transforms the text to the format Javascript accepts (double quote to \\\"). 

In Find-transform, the usage experience of predefined variable ${Input} is not as good as the vscode build-in find&reaplace box which can realtime highlight the consequence found and it does not support right-click context menus such as copy and paste(or support not so well).

**Comment by ArturoDent** [comment]
You want to start with some text in the Find widget and modify that text and put it back into the Find widget and then run that new find?

**Comment by ArturoDent** [comment]
Are you referring to using the `${getFindInput}` option?

**Comment by Haale** [comment]
> I see there is a setting which prevents the quickInput from closing when you right-click on it:
> 
> ```
> Workbench > Quick Open: Close on Focus Lost  // disable this
> ```
> 
> Then you can paste into it using its context menu.
> 
> Open issue on vscode github: [Cannot right click on command palette-like panels](https://github.com/microsoft/vscode/issues/153267)

The problem of context menu loss is settled in your lead.
However,my regx pattern doesn't work yet.
Here is my regular expression:
`(?<=Element\sname="Topic".\n\s*.)Attributes.\n(?=<Attr)`
you may note that's a multiline matching regx that does the job in vscode built-in Find widget while fails in ${getFindInput}. The **\n** cannot work in the variable ${getFindInput}(I guess the **\n** not escape to the **\\n** in Find-and-Transform)

**Comment by ArturoDent** [comment]
Often the problem is backslashes as you may have to do single, double or even more in the extension code depending on the input route.  But in this case it is the unique way that vscode handles newlines in finds.  

Your regex works in the Find widget because vscode changes it to this behind the scenes:

```
(?<=Element\sname="Topic".\r?\n\s*.)Attributes.\n(?=<Attr)   // note the added \r?
```

If you use that regex with `${getFindInput}` then it works.  I thought I had matched vscode's in-built behaviour by replacing any `\n` with `\r?\n` (which is what vscode does) but I hadn't accounted for vscode automatically double-backslashing input that it gets from an InputBox first.  So it transforms the input into:

```
(?<=Element\\sname=\"Topic\".\\n\\s*.)Attributes.\\n(?=<Attr)
```
which in my brief testing I can fix by also replacing `\\n` with `\r?\n`.  I just need to do more testing.

**Comment by ArturoDent** [comment]
Try v4.8.2 to see if that works for you.
