### ISSUE TITLE
Screen scrolls back to cursor if cursor out of screen when using `preserveSelections`: true

### ISSUE THREAD

**Issue by zqstack** [ArturoDent/find-and-transform#26]
**Issue**
When editing a JS file using the settings below and changes are applied by `find-and-transform` and the cursor is outside of the current view, when using `"preserveSelections": true`, the view scrolls back to the cursor.

**Video**
![Animation](https://github.com/ArturoDent/find-and-transform/assets/60988202/3b01d56f-b1a8-47d6-9fae-6e5f0830d8a8)

**Explanation**
I am using `"preCommands": "editor.action.formatDocument"` to first apply changes from the default VSCode formatter, which seems to be causing this effect. But once I remove it, it won't apply changes than this one if it finds them.

With reference to: https://stackoverflow.com/a/77991779/5437864

**settings.json**
```
{
	"findInCurrentFile": {
		"AddSpaceAround&&and||": {
			"title": "add a space around && and ||",
			"find": "(?<=[^\\s]\\s)(&&|\\|\\|)(?=\\s[^\\s])",
			"replace": " $1 ",
			"isRegex": true,
			"preserveSelections": true,
			"preCommands": "editor.action.formatDocument",
		}
	},
	"[javascript][typescript]": {
		"editor.codeActionsOnSave": [
			"source.AddSpaceAround&&and||",
		]
	}
}
```

**Comment by ArturoDent** [comment]
Give v5.3.0 a try.  I believe your issue is fixed.  Here is a demo of 2 codeActions being applied and the first has the `"preCommands": "editor.action.formatDocument",` option.


![formatCodeAction](https://github.com/ArturoDent/find-and-transform/assets/31813701/02cdd22c-5d7a-4d9f-af2f-22edc9319606)

There are two settings which might be affecting you:

> Javascript > Format: Insert Space Before and After Binary Operators
> Typescript > Format: Insert Space Before and After Binary Operators

These will remove the extra space you want around `&&` and `||` unless these options are disabled.  Or you could disable formatting on save in your settings like this:

```jsonc
  "[typescript][javascript]": {
    "editor.codeActionsOnSave": [
      "source.AddSpaceAround&&and||",
      "source.ModifyAsterisks"
    ],
       // add this so the binary formatting options don't remove spaces added by the codeAction
    "editor.formatOnSave": false       
  },
```

**Comment by ArturoDent** [comment]
Closing as dirty file fixed after `codeActionsOnSave`.  And scroll on format is a built-in feature of vscode that the extension cannot "fix".
