### ISSUE TITLE
Looking to use this tool to help with csv selections

### ISSUE THREAD

**Issue by AdamMarciniak** [ArturoDent/find-and-transform#3]
Hey great project! I'm working with a csv file and would like to do a multi line select on certain values between commas. For example:

apple fritter, pear, banana
string, shoe, elephant,
1, 2, 3

I'd like to do a multi select on apple fritter, string, 1 so I can put a cursor before and after them
Then I'd like to go to the next occurence of stuff between commas which would select pear, shoe, 2 
and continue on. 

How would I write the key binding to do that?

**Comment by ArturoDent** [comment]
You want two cursors (the `|`'s below) like:

```
|apple fritter|, pear, banana
|string|, show, elephant
|1|, 2, 3
```

and then 

```
apple fritter, |pear|, banana
string, |show|, elephant
1, |2|, 3
```

and so on?

**Comment by AdamMarciniak** [comment]
Yes like that :) The cursors can be there either simultaneously or one after the other. 
Basically I have lots of rows of CSV data where some "columns" need quotes around them. If I can select what's inside the columns with a multiline select and have it move to the next "column" on each round then I can easily add the quotes.

**Comment by ArturoDent** [comment]
It took a little while because I found a couple of bugs in the meantime.  Use these two keybindings in your `keybinndings.json`:

```jsonc
{
  "key": "alt+f",                     // whatever keybinding you want
  "command": "findInCurrentFile",
  "args": {
    "find": "(?<=,\\s|^)([\\w ]+)(?!.*\")",
    "isRegex": true,                  // no replace
    "cursorMoveSelect": "$1",         // important, to select the $1 capture group
    "restrictFind": "once"            // just do first match after cursor 
  }
},

{
  "command": "findInCurrentFile",
  "key": "alt+'",
  "args": {
    "replace": "\"${selectedText}\"",   // no find!
    "restrictFind": "line"              // line
  }
}
```

Here is a demo:  

![fritter](https://user-images.githubusercontent.com/31813701/159190763-24ff7e71-b838-45b5-9ae7-ce43f3296ad9.gif)

So you first need to put a cursor on all the lines you want to work on - at the beginning of the lines.

Then, `alt+f` to select the next match, `alt+'` to surround that match with quotes **or** `alt+f` again to skip and select the next match.

The only issue right now is if there are duplicates on a line, like:

    apple fritter, pear fruit, apple fritter

then both of those `apple fritters` would be quoted when the first one is - I'll have to look into that more...

Let me know if this works for you.  Thanks.

**Comment by ArturoDent** [comment]
Closing as fixed.
